version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      - PORT=8000

  frontend:
    build: 
      context: ./frontend
      platform: linux/amd64
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
    depends_on:
      - backend