stages:
  data_collection:
    cmd: python ./src/data_collection.py
    deps:
      - ./src/data_collection.py
    outs:
      - /home/hababi/data/raw:
          cache: false
  
  data_preparation:
    cmd: python ./src/data_preparation.py
    deps:
    - ./src/data_preparation.py
    outs:
      - /home/hababi/data/processed:
          cache: false

  model_building:
    cmd: python ./src/model_building.py
    deps:
      - /home/hababi/data/processed
      - ./src/model_building.py

  model_registration:
    cmd: python ./src/model_reg.py
    deps:
    - ./models/run_info.json
    - ./src/model_reg.py